server:
  port: 8888
logging:
  level:
    org.springframework.cloud.config.client: DEBUG
    org.springframework.cloud.config.server: DEBUG
spring:
  application:
    name: 'server-config'
  profiles:
    active: composite,native
  cloud:
    config:
      server:
        composite:
          - type: native
            search-locations: file:/config/common

          - type: native
            search-locations: file:/config

          - type: native
            search-locations:
              - file:/config/common
              - file:/config/{application}
              - file:/config
    bus:
      enabled: true

  rabbitmq: # RabbitMQ kapcsolat
    host: ${global.monitoring.rabbitmq.host}
    port: ${global.monitoring.rabbitmq.port}
    username: ${global.monitoring.rabbitmq.username}
    password: ${global.monitoring.rabbitmq.password}
    virtual-host: ${global.monitoring.rabbitmq.virtual-host}
debug: true


eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: busrefresh, busenv, refresh