server:
  port: 15043
spring:
  config:
    import:
      - ${global.paths.config-repo}/common/eureka.yaml
      - ${global.paths.config-repo}/common/tracing.yaml
      - ${global.paths.config-repo}/common/monitoring.yaml
      - ${global.paths.config-repo}/common/logging.yaml
      - ${global.paths.config-repo}/common/db.yaml
#      - ${global.paths.config-repo}/common/session.yaml
      #      - ${global.paths.config-repo}/common/upload.yaml
      - ${global.paths.config-repo}/common/configuration-bus-client.yaml
    debug: true
#  cloud:
#    function:
#      definition: queueExecutionTaskProcessingItemRead;queueHistoryBroadcast
#    stream:
#      bindings:
#        queueExecutionTaskProcessingItemRead-out-0:
#          destination: ai-liz-concept-execution-task-processing-exchange
#        queueExecutionTaskProcessingItemRead-in-0:
##          content-type: application/json
#          destination: ai-liz-concept-execution-task-processing-exchange
#          group: ai-liz-concept-execution-task-processing-queue
#          consumer:
#            concurrency: 1
##           queueName: ai-liz-concept-execution-task-processing-queue
#        queueHistoryBroadcast-in-0:
#          destination: history-broadcast-main
#          group: ai-liz-history-queue
#          contentType: application/json
#
#      rabbit:
#        bindings:
#
#          queueExecutionTaskProcessingItemRead-out-0:
#            producer:
#              routingKey: route-main
#              exchangeType: direct
##              persistentDeliveryMode: true
#          queueExecutionTaskProcessingItemRead-in-0:
#            consumer:
#              bindingRoutingKey: route-main
#              exchangeType: direct
#              acknowledgeMode: AUTO
#
#          queueHistoryBroadcast-in-0:
#            consumer:
#              bindingRoutingKey: x-route
#              exchangeType: topic
#              acknowledgeMode: AUTO
#      binders:
#        rabbit:
#          type: rabbit
#          environment:
#            spring:
#              rabbitmq:
#                host: localhost
#                port: 5672
#                username: guest
#                password: guest
#                virtual-host: /
