server:
  port: 7010

spring:
  application:
    name: 'ai1'
  config:
    import: 'optional:configserver:'

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:7001/eureka'

management:
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'