<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>hu.kalmancheysandor.applications.dominions</groupId>
        <artifactId>dominions-root</artifactId>
        <version>1.0-SNAPSHOT</version>
        <relativePath>../../../pom.xml</relativePath>
    </parent>

    <artifactId>api-ai-neural</artifactId>

    <properties>
        <stanford-corenlp.version>4.5.3</stanford-corenlp.version>
        <opennlp-tools.version>2.1.1</opennlp-tools.version>
        <neuroph.version>2.92</neuroph.version>
    </properties>

    <dependencies>
        <!-- .......GENERAL.......-->
        <dependency>
            <groupId>hu.kalmancheysandor.applications.dominions</groupId>
            <artifactId>api-general</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
        <!-- .......AI.......-->
        <dependency>
            <groupId>hu.kalmancheysandor.applications.dominions</groupId>
            <artifactId>api-ai-common</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>edu.stanford.nlp</groupId>
            <artifactId>stanford-corenlp</artifactId>
            <version>${stanford-corenlp.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.opennlp</groupId>
            <artifactId>opennlp-tools</artifactId>
            <version>${opennlp-tools.version}</version>
        </dependency>
        <dependency>
            <groupId>org.beykery</groupId>
            <artifactId>neuroph</artifactId>
            <version>${neuroph.version}</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <configuration>
                    <archive>
                        <manifestEntries>

                        </manifestEntries>
                    </archive>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>