server:
  port: 15048
  session:
    timeout: 30m  # Set session timeout to 30 minutes

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  level:
     org.springframework.security: DEBUG
     org.springframework.cloud.stream.binding: DEBUG
     com.fasterxml.jackson.databind: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:15001/eureka'

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans



spring:
  application:
    name: 'server-ai-egon'
  config:
    import: 'optional:configserver:'
#
#  datasource:
#
#    # Case-1: No container in use
#    url: jdbc:mysql://127.0.0.1:3306/dominions?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true
#
#    # Case-2: Only database is in container
#    #url: jdbc:mysql://127.0.0.1:3310/webshop?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true
#
#    # Case-3: containers are in use
#    #   url: jdbc:mysql://webshop_db_container/webshop?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true
#    username: root
#    password: CHANGE_ME
#  jpa:
#    show: true
#    hibernate:
#      ddl-auto: validate
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#    show-sql: on
#
#  session:
#    store-type: jdbc
#    jdbc:
#      initialize-schema: always # Táblák automatikus létrehozása

#  servlet:
#    multipart:
#      max-file-size: -1
#      max-request-size: -1
#  cloud:
#    stream:
#      bindings:
#        test-out-0:
#          destination: my-test-destination
#        myTest-in-0:
#          destination: my-test-destination
#          group: my-test-queue
#          consumer:
#            concurrency: 2
#      rabbit:
#        bindings:
#
#          test-out-0:
#            producer:
#              routingKeyExpression: '''my-test-key'''
#          myTest-in-0:
#            consumer:
#              bindingRoutingKey: '''my-test-key'''
#              queue-name-group-only: true
#      binders:
#        rabbit:
#          type: rabbit
#          environment:
#            spring:
#              rabbitmq:
#                host: localhost
#                port: 5672
#                username: guest
#                password: guest

  #  mail:
  #    host: CHANGE_ME
  #    port: 587
  #    username: "61e63cc99e6aed4fd5a250944d208d3b"
  #    password: "71636c53537d3f5d8d46f02df58ef5cc"
  #    properties:
  #      mail:
  #        smtp:
  #          auth: true
  #          starttls:
  #            enable: true

#  mail:
#    host: CHANGE_ME
#    port: 25
#    username: CHANGE_ME
#    password: jwYur520f0he
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: false
  debug: true
