spring:
  rabbitmq:
    host: ${global.monitoring.rabbitmq.host}
    port: ${global.monitoring.rabbitmq.port}
    username: ${global.monitoring.rabbitmq.username}
    password: ${global.monitoring.rabbitmq.password}
    virtual-host: ${global.monitoring.rabbitmq.virtual-host}

  cloud:
    bus:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: busrefresh, busenv, refresh,health