app:
  datasource:
    main:
      jdbc-url: jdbc:mysql://CHANGE_ME:3306/dominions?createDatabaseIfNotExist=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true
      username: root
      password: CHANGE_ME
      hikari:
        transaction-isolation: TRANSACTION_REPEATABLE_READ
    session:
      jdbc-url: jdbc:mysql://CHANGE_ME:3306/dominions_session?createDatabaseIfNotExist=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true
      username: root
      password: CHANGE_ME
      hikari:
        transaction-isolation: TRANSACTION_REPEATABLE_READ
    ai-liz:
      jdbc-url: jdbc:mysql://CHANGE_ME:3306/dominions_ai_liz?createDatabaseIfNotExist=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true
      username: root
      password: CHANGE_ME
      hikari:
        transaction-isolation: TRANSACTION_REPEATABLE_READ

    ai-hugo:
      jdbc-url: jdbc:mysql://CHANGE_ME:3306/dominions_ai_hugo?createDatabaseIfNotExist=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true
      username: root
      password: CHANGE_ME
      hikari:
        transaction-isolation: TRANSACTION_REPEATABLE_READ

spring:
#  datasource:
#
#    # Case-1: No container in use
#    jdbc-url: jdbc:mysql://127.0.0.1:3306/dominions?createDatabaseIfNotExist=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true
#
#    # Case-2: Only database is in container
#    #url: jdbc:mysql://127.0.0.1:3310/webshop?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true
#
#    # Case-3: containers are in use
#    #   url: jdbc:mysql://webshop_db_container/webshop?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true
#    username: root
#    password: CHANGE_ME
  jpa:
    show: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: on