logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.stream.binding: DEBUG
    com.fasterxml.jackson.databind: DEBUG
    org.springframework.cloud.gateway: DEBUG

    org.springframework.cloud.stream: DEBUG
    org.springframework.amqp: DEBUG