#spring:
#  rabbitmq:
#    host: ${global.monitoring.rabbitmq.host}
#    port: ${global.monitoring.rabbitmq.port}
#    username: ${global.monitoring.rabbitmq.username}
#    password: ${global.monitoring.rabbitmq.password}
#    virtual-host: ${global.monitoring.rabbitmq.virtual-host}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://server-zipkin:9411/api/v2/spans