server:
  session:
    timeout: 1m  # Set session timeout to 30 minutes

spring:
  session:
    store-type: jdbc
    timeout: 1m
    jdbc:
      table-name: SPRING_SESSION      # This is ignored when the schema is created with "create" or "create-drop". It is only applied if the table was created manually.
      attributes-table-name: SPRING_SESSION_ATTRIBUTES # This is ignored when the schema is created in "always" mode. It is only taken into account if the table was created manually.
      initialize-schema: always  # Automatic creation of session related tables

