services:

  server-config:
    build: ./server-config
    ports:
      - "8888:8888"
    env_file:
      - .env
    environment:
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx512m"
    volumes:
      - ${CENTRAL_CONFIG_REPO_PATH}:/config
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10

  server-gateway:
    build: ./server-gateway
    ports:
      - "15000:15000"
    env_file:
      - .env
    environment:
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx512m"
    depends_on:
      server-config:
        condition: service_healthy



  server-eureka:
    build: ./server-eureka
    ports:
      - "15001:15001"
    env_file:
      - .env
    environment:
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx512m"
    depends_on:
      server-config:
         condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15001/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10



  server-auth:
    build: ./server-auth
    ports:
      - "15002:15002"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx512m"
    depends_on:
      server-config:
        condition: service_healthy

  server-site:
    build: ./server-site
    ports:
      - "15009:15009"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx512m"
    volumes:
      - ${HOST_GLOBAL_DATA_FOLDER}:${APP_GLOBAL_DATA_FOLDER}
    depends_on:
      server-config:
        condition: service_healthy

  server-admin:
    build: ./server-admin
    ports:
      - "15010:15010"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx512m"
    volumes:
      - ${HOST_GLOBAL_DATA_FOLDER}:${APP_GLOBAL_DATA_FOLDER}
    depends_on:
      server-config:
        condition: service_healthy

  server-game:
    build: ./server-game
    ports:
      - "15020:15020"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx512m"
    depends_on:
      server-config:
        condition: service_healthy

  server-mailing:
    build: ./server-mailing
    ports:
      - "15099:15099"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx512m"
    depends_on:
      server-config:
        condition: service_healthy

  server-monitoring:
    build: ./server-monitoring
    ports:
      - "15500:15500"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx512m"
    depends_on:
      server-config:
        condition: service_healthy

  server-ai-hugo-operation:
    build: ./server-ai-hugo-operation
    ports:
      - "15801:15043"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx512m"
    depends_on:
      server-config:
        condition: service_healthy

  server-ai-hugo-agent-1:
    build: ./server-ai-hugo-agent
    ports:
      - "15802:15044"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx2048m -Xms512m -Xss4m"
    depends_on:
      server-config:
        condition: service_healthy

  server-ai-hugo-agent-2:
    build: ./server-ai-hugo-agent
    ports:
      - "15803:15044"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx2048m -Xms512m -Xss4m"
    depends_on:
      server-config:
        condition: service_healthy

  server-ai-liz-operation:
    build: ./server-ai-liz-operation
    ports:
      - "15851:15042"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx2048m -Xms512m -Xss4m"
    depends_on:
      server-config:
        condition: service_healthy

  server-ai-liz-agent-1:
    build: ./server-ai-liz-agent
    ports:
      - "15852:15041"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx2048m -Xms512m -Xss4m"
    depends_on:
      server-config:
        condition: service_healthy

  server-ai-liz-agent-2:
    build: ./server-ai-liz-agent
    ports:
      - "15853:15041"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx2048m -Xms512m -Xss4m"
    depends_on:
      server-config:
        condition: service_healthy

  server-zipkin:
    image: openzipkin/zipkin
    container_name: server-zipkin
    ports:
      - "9411:9411"
    restart: unless-stopped