services:





  server-config:
    build: ./server-config
    ports:
      - "8888:8888"
    volumes:
      - CHANGE_ME:/config
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10



  server-gateway:
    build: ./server-gateway
    ports:
      - "15000:15000"
    depends_on:
      server-config:
        condition: service_healthy
  #      server-eureka:
  #        condition: service_healthy


  server-eureka:
    build: ./server-eureka
    ports:
      - "15001:15001"
    depends_on:
      server-config:
         condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15001/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10



  server-auth:
    build: ./server-auth
    ports:
      - "15002:15002"
    extra_hosts:
      - "CHANGE_ME:host-gateway"
    depends_on:
      server-config:
        condition: service_healthy
#      server-eureka:
#        condition: service_healthy

  server-site:
    build: ./server-site
    ports:
      - "15009:15009"
    extra_hosts:
      - "CHANGE_ME:host-gateway"
    depends_on:
      server-config:
        condition: service_healthy
#      server-eureka:
#        condition: service_healthy

  server-admin:
    build: ./server-admin
    ports:
      - "15010:15010"
    extra_hosts:
      - "CHANGE_ME:host-gateway"
    depends_on:
      server-config:
        condition: service_healthy
#      server-eureka:
#        condition: service_healthy


  server-game:
    build: ./server-game
    ports:
      - "15020:15020"
    extra_hosts:
      - "CHANGE_ME:host-gateway"
    depends_on:
      server-config:
        condition: service_healthy
#      server-eureka:
#        condition: service_healthy

  server-mailing:
    build: ./server-mailing
    ports:
      - "15099:15099"
    extra_hosts:
      - "CHANGE_ME:host-gateway"
    depends_on:
      server-config:
        condition: service_healthy
#      server-eureka:
#        condition: service_healthy

  server-monitoring:
    build: ./server-monitoring
    ports:
      - "15500:15500"
    extra_hosts:
      - "CHANGE_ME:host-gateway"
    depends_on:
      server-config:
        condition: service_healthy
#      server-eureka:
#        condition: service_healthy

  server-rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15600:5672"
      - "15601:15672"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 10