<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>hu.kalmancheysandor.applications.dominions</groupId>
        <artifactId>dominions-root</artifactId>
        <version>1.0-SNAPSHOT</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>

    <artifactId>server-admin</artifactId>

    <dependencies>

        <!-- .......COMMON.......-->
        <dependency>
            <groupId>hu.kalmancheysandor.applications.dominions</groupId>
            <artifactId>api-server-all</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>hu.kalmancheysandor.applications.dominions</groupId>
            <artifactId>api-server-common</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>hu.kalmancheysandor.applications.dominions</groupId>
            <artifactId>api-server-authentication-common</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>

        <!--.......USER.......-->
        <dependency>
            <groupId>hu.kalmancheysandor.applications.dominions</groupId>
            <artifactId>api-server-user-admin</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>hu.kalmancheysandor.applications.dominions</groupId>
            <artifactId>api-server-user-site</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>


        <!--.......WEBSOCKET.......-->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-websocket</artifactId>
        </dependency>

<!--        <dependency>-->
<!--            <groupId>org.springframework.cloud</groupId>-->
<!--            <artifactId>spring-cloud-starter-bus-amqp</artifactId>-->
<!--        </dependency>-->

<!--        <dependency>-->
<!--            <groupId>org.springframework.boot</groupId>-->
<!--            <artifactId>spring-boot-starter-actuator</artifactId>-->
<!--        </dependency>-->


        <!--.......GAME.......-->
        <dependency>
            <groupId>hu.kalmancheysandor.applications.dominions</groupId>
            <artifactId>api-server-game-common</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
    </dependencies>

</project>