<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>hu.kalmancheysandor.applications.dominions</groupId>
        <artifactId>dominions-root</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>server-ai-helga</artifactId>

    <dependencies>

        <!-- .......GENERAL.......-->
        <dependency>
            <groupId>hu.kalmancheysandor.applications.dominions</groupId>
            <artifactId>api-general</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>

        <!-- .......COMMON.......-->
        <dependency>
            <groupId>hu.kalmancheysandor.applications.dominions</groupId>
            <artifactId>api-server-common</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>hu.kalmancheysandor.applications.dominions</groupId>
            <artifactId>api-server-ai-common</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>hu.kalmancheysandor.applications.dominions</groupId>
            <artifactId>api-server-game-common</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>

        <!-- .......AI.......-->
        <dependency>
            <groupId>hu.kalmancheysandor.applications.dominions</groupId>
            <artifactId>api-ai-common</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>hu.kalmancheysandor.applications.dominions</groupId>
            <artifactId>api-ai-neural</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>hu.kalmancheysandor.applications.dominions</groupId>
            <artifactId>api-ai-helga</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>


        <!--.......DATABASE.......-->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>8.0.25</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <configuration>
                    <archive>
                        <manifestEntries>

                        </manifestEntries>
                    </archive>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>